
# Purpose: Build and Validation

name: Continuous Integration

on:
  push:
    branches:
      - dev
      - test

permissions:
    contents: read # Allows my workflow to read my repo files

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout Repository
         uses: actions/checkout@v4 # Checkout source code
      
      -  name: Verify Repository Checkout
         run: ls -la

      -  name: Verify Required Project Files
         run: |
           ls index.html
           ls style.css
           ls script.js